### ISSUE TITLE
A new major version 0.6 is preparing

### ISSUE THREAD

**Issue by Tim-Zhang** [containerd/ttrpc-rust#119]
We plan to release a new major version 0.6 to include some incompatible changes, e.g. make some helper methods private, and the incompatible change https://github.com/containerd/ttrpc-rust/pull/116

I have created the branch 0.5.0 for maintain it continuously, and from now on the master branch is belong to version 0.6 

@jodh-intel @mxpv @liubin @teawater @lifupan feel free to propose incompatible pr or refactor in this period.

I plan to release the version <s>in this weekend</s> at the beginning of January 2022

- [x] https://github.com/containerd/ttrpc-rust/pull/116
- [x] https://github.com/containerd/ttrpc-rust/pull/120
- [x] https://github.com/containerd/ttrpc-rust/pull/121
- [x] https://github.com/containerd/ttrpc-rust/pull/128
- [x] https://github.com/containerd/ttrpc-rust/pull/118
- [x] https://github.com/containerd/ttrpc-rust/pull/129
- [ ] publish the version 0.6.0

**Comment by jodh-intel** [comment]
> We plan to release a new major version 0.6 to include some incompatible changes,

What is the plan here to allow users of this crate to deal with the incompatible API?

Since rust uses [semver](https://semver.org/), bumping from 0.5.x to 0.6 should not change the API in an incompatible manner so strictly we should either:

- Release 1.0.0 with these API incompatible changes.
- Continue to support the old address format and add new API's to 0.6 for the new socket handling (since that won't break existing users).

**Comment by Tim-Zhang** [comment]
@jodh-intel The version 0.6 is not compatible with 0.5 according to https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#caret-requirements 

An update is allowed if the new version number does not modify the **left-most non-zero** digit in the major, minor, patch grouping

**Comment by Tim-Zhang** [comment]
After discussed with @liubin the release of 0.6 Will be delayed until early January 2022. Because we have many PR and the Christmas holiday and the New Year's Day holiday is coming soon.
