### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by mxpv** [containerd/ttrpc-rust#132]
There is a desire to get Windows support in https://github.com/containerd/rust-extensions/issues/4. Since the shim crate mainly depends on ttrpc-rust, I think it make sense to add windows support / CI checks here first.
Opening issue mainly for tracking (unfortunately I don't have proper environment to implement this).

**Comment by jsturtevant** [comment]
I am going to start to look into this

**Comment by jsturtevant** [comment]
the [proto source generation](https://github.com/containerd/ttrpc-rust#1-generate-with-protoc-command) works:

```
protoc --rust_out=. --ttrpc_out=. --plugin=protoc-gen-ttrpc=C:\Users\user\.cargo\bin\ttrpc_rust_plugin.exe .\oci.proto
```

Building doesn't not mainly due to the `nix` package

```rust
cargo build
Some errors have detailed explanations: E0412, E0422, E0425, E0432, E0433.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `ttrpc` due to 58 previous errors
```

**Comment by jsturtevant** [comment]
Confirmed the [programmatic approach](https://github.com/containerd/ttrpc-rust#2-generate-programmatically) to source generate works as well.

**Comment by jsturtevant** [comment]
After looking into this a bit, It looks like the current approach in this library mostly uses some form of *nix Domain sockets:

https://github.com/containerd/ttrpc-rust/blob/af10ad4eddc2e5d474d28d871ba8a8814cca3cfa/src/lib.rs#L29-L39

My first idea was to use [Windows Unix Domain Socket](https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/) compatibility to make the integration fairly straightforward.

After looking into a bit more (and talking with @cpuguy83) I realized that Containerd on Windows doesn't currently support UDS only named pipes on Windows, which is one of the big use cases for this library.

My current thoughts are to use https://github.com/tokio-rs/mio to integrate support for named pipes first.  I choose library as there is already a indirect dependency through [tokio package](https://github.com/containerd/ttrpc-rust/blob/af10ad4eddc2e5d474d28d871ba8a8814cca3cfa/Cargo.toml#L22).  Later if there was desire for other use cases beyond Containerd (where is strictly windows named pipes) we could use https://github.com/Azure/mio-uds-windows or https://github.com/tokio-rs/mio/pull/1610 to integrate the UDS support.

@cpuguy83 @mxpv thoughts? I am new to Rust and these projects so if there is another direction, I should take let me know otherwise I will take a go at this and see what it looks like.

**Comment by jsturtevant** [comment]
quick update, I got the `sync` project working on windows. I am cleaning it up and adding a build step and should have something to share for feedback soon
